# -*- coding: utf-8 -*-
"""YFinance_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0eZsc8liSqsUwCaoXTf5vit2fkSlYRK
"""

import yfinance as yf
import pandas as pd

def get_returns(pricevec):
    n = len(pricevec)
    ratiovec = pricevec[1:n] / pricevec[:n-1]
    returns = ratiovec - 1
    return returns


ticker = 'GS'
start_date = '2024-01-01'
end_date = '2024-01-31'


df = yf.download(ticker, start=start_date, end=end_date)


if 'Adj Close' not in df.columns:
    df['Adj Close'] = df['Close']


returns = get_returns(df['Adj Close'].values)

df['Lagging Return'] = pd.Series(returns, index=df.index[1:])

df['Lagging Return'] = df['Lagging Return'].fillna(0)

print(df)

